name: pr-agent

on:
    pull_request:
      types: [opened, reopened, ready_for_review]
jobs:
    pr_agent_job:
      runs-on: ubuntu-latest
      
      steps:
        - name: PR Agent action step
          id: pragent
          uses: Codium-ai/pr-agent@main
          env:
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            CONFIG.MODEL: "gpt-4o-mini"
            CONFIG.MODEL_TURBO: "gpt-3.5-turbo"
            CONFIG.FALLBACK_MODELS: "gpt-4o-mini-2024-07-18"
            github_action_config.auto_review: "true" # enable\disable auto review
            github_action_config.auto_describe: "true" # enable\disable auto describe
            github_action_config.auto_improve: "true" # enable\disable auto improve