name: pr-workflow

on:
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  swiftLint:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: "create-main-branch"
        run: "git branch --track main origin/main"
  
      # Runs a single command using the runners shell
      - name: SwiftLint
        uses: yannpom/action-swiftlint@v1
        env: 
          DIFF_BASE: ${{ github.base_ref }}
