name: pr-workflow

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  swiftLint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:5.5-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git status
        run: |
          git status
          
      # Runs a single command using the runners shell
      - name: SwiftLint
        run: |
          sh ci_scripts/lint_changed_files.sh

