name: pr-workflow

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  swiftLint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:5.5-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get Changed Files
        id: get_changed_files
        run: |
          echo "$(pwd)" |
          echo "$(git diff --name-only main..HEAD | grep '\.swift$' || true)"

      # Runs a single command using the runners shell
      - name: SwiftLint
        run: |
          set -o pipefail |
          git diff --name-only main..HEAD \
          | grep '\.swift$' \
          | xargs -I% swiftlint lint --strict --quiet  codeclimate "%" | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'
